/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuiviCommandeRouteImport } from './routes/suivi-commande'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoutiqueIndexRouteImport } from './routes/boutique.index'
import { Route as CommandePaiementRouteImport } from './routes/commande.paiement'
import { Route as CommandeCoordonneesRouteImport } from './routes/commande.coordonnees'
import { Route as CommandeConfirmationRouteImport } from './routes/commande.confirmation'
import { Route as BoutiqueSlugRouteImport } from './routes/boutique.$slug'

const SuiviCommandeRoute = SuiviCommandeRouteImport.update({
  id: '/suivi-commande',
  path: '/suivi-commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueIndexRoute = BoutiqueIndexRouteImport.update({
  id: '/boutique/',
  path: '/boutique/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandePaiementRoute = CommandePaiementRouteImport.update({
  id: '/commande/paiement',
  path: '/commande/paiement',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeCoordonneesRoute = CommandeCoordonneesRouteImport.update({
  id: '/commande/coordonnees',
  path: '/commande/coordonnees',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeConfirmationRoute = CommandeConfirmationRouteImport.update({
  id: '/commande/confirmation',
  path: '/commande/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueSlugRoute = BoutiqueSlugRouteImport.update({
  id: '/boutique/$slug',
  path: '/boutique/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/galerie': typeof GalerieRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/commande/coordonnees': typeof CommandeCoordonneesRoute
  '/commande/paiement': typeof CommandePaiementRoute
  '/boutique/': typeof BoutiqueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/galerie': typeof GalerieRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/commande/coordonnees': typeof CommandeCoordonneesRoute
  '/commande/paiement': typeof CommandePaiementRoute
  '/boutique': typeof BoutiqueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/galerie': typeof GalerieRoute
  '/inscription': typeof InscriptionRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/panier': typeof PanierRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/suivi-commande': typeof SuiviCommandeRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/commande/coordonnees': typeof CommandeCoordonneesRoute
  '/commande/paiement': typeof CommandePaiementRoute
  '/boutique/': typeof BoutiqueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/connexion'
    | '/contact'
    | '/favoris'
    | '/galerie'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reset-password'
    | '/services'
    | '/suivi-commande'
    | '/boutique/$slug'
    | '/commande/confirmation'
    | '/commande/coordonnees'
    | '/commande/paiement'
    | '/boutique/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/connexion'
    | '/contact'
    | '/favoris'
    | '/galerie'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reset-password'
    | '/services'
    | '/suivi-commande'
    | '/boutique/$slug'
    | '/commande/confirmation'
    | '/commande/coordonnees'
    | '/commande/paiement'
    | '/boutique'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/connexion'
    | '/contact'
    | '/favoris'
    | '/galerie'
    | '/inscription'
    | '/mot-de-passe-oublie'
    | '/panier'
    | '/reset-password'
    | '/services'
    | '/suivi-commande'
    | '/boutique/$slug'
    | '/commande/confirmation'
    | '/commande/coordonnees'
    | '/commande/paiement'
    | '/boutique/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  FavorisRoute: typeof FavorisRoute
  GalerieRoute: typeof GalerieRoute
  InscriptionRoute: typeof InscriptionRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  PanierRoute: typeof PanierRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SuiviCommandeRoute: typeof SuiviCommandeRoute
  BoutiqueSlugRoute: typeof BoutiqueSlugRoute
  CommandeConfirmationRoute: typeof CommandeConfirmationRoute
  CommandeCoordonneesRoute: typeof CommandeCoordonneesRoute
  CommandePaiementRoute: typeof CommandePaiementRoute
  BoutiqueIndexRoute: typeof BoutiqueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suivi-commande': {
      id: '/suivi-commande'
      path: '/suivi-commande'
      fullPath: '/suivi-commande'
      preLoaderRoute: typeof SuiviCommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/': {
      id: '/boutique/'
      path: '/boutique'
      fullPath: '/boutique/'
      preLoaderRoute: typeof BoutiqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/paiement': {
      id: '/commande/paiement'
      path: '/commande/paiement'
      fullPath: '/commande/paiement'
      preLoaderRoute: typeof CommandePaiementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/coordonnees': {
      id: '/commande/coordonnees'
      path: '/commande/coordonnees'
      fullPath: '/commande/coordonnees'
      preLoaderRoute: typeof CommandeCoordonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/confirmation': {
      id: '/commande/confirmation'
      path: '/commande/confirmation'
      fullPath: '/commande/confirmation'
      preLoaderRoute: typeof CommandeConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/$slug': {
      id: '/boutique/$slug'
      path: '/boutique/$slug'
      fullPath: '/boutique/$slug'
      preLoaderRoute: typeof BoutiqueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  FavorisRoute: FavorisRoute,
  GalerieRoute: GalerieRoute,
  InscriptionRoute: InscriptionRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  PanierRoute: PanierRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SuiviCommandeRoute: SuiviCommandeRoute,
  BoutiqueSlugRoute: BoutiqueSlugRoute,
  CommandeConfirmationRoute: CommandeConfirmationRoute,
  CommandeCoordonneesRoute: CommandeCoordonneesRoute,
  CommandePaiementRoute: CommandePaiementRoute,
  BoutiqueIndexRoute: BoutiqueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
